acme_app_test:
    resource:     "@ACMEAppBundle/Controller/TestController.php"
    type:         annotation
    prefix:       /app
    options:
        frontend: true

acme_app_bundle_api:
    resource:     "@ACMEAppBundle/Resources/config/oro/routing_api.yml"
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest